print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/mattpoast/Desktop/Repo/DGM1620FALL2019/3d_progect/Assets/70'sRoom.mb"`)
{		
	file -o "/Users/mattpoast/Desktop/Repo/DGM1620FALL2019/3d_progect/Assets/70'sRoom.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/mattpoast/Desktop/Repo/DGM1620FALL2019/3d_progect/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/mattpoast/Desktop/Repo/DGM1620FALL2019/3d_progect/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/mattpoast/Desktop/Repo/DGM1620FALL2019/3d_progect/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
